# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(383, 523)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        MainWindow.setStyleSheet("background: transparent;\n"
"border: none;\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 100, 381, 464))
        self.gridLayoutWidget.setStyleSheet("QPushButton {\n"
"    background-color: #007BFF;\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    border-radius: 10px;\n"
"    padding: 10px 20px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004080;\n"
"}\n"
"")
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: #666666;\n"
"    color: white;\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"    border: 1px solid #303030;\n"
"    border-radius: 0px;\n"
"    padding: 20px;\n"
"    min-width: 30px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5A5A5A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6A6A6A;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 4, 0, 1, 1)
        self.pushButton_plus = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_plus.setStyleSheet("QPushButton {\n"
"    background-color: #ffb833;\n"
"    color: white;\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"    border: 1px solid #303030;\n"
"    border-radius: 0px;\n"
"    padding: 20px;\n"
"    min-width: 30px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5A5A5A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6A6A6A;\n"
"}")
        self.pushButton_plus.setObjectName("pushButton_plus")
        self.gridLayout_2.addWidget(self.pushButton_plus, 5, 3, 1, 1)
        self.pushButton_division = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_division.setStyleSheet("QPushButton {\n"
"    background-color: #ffb833;\n"
"    color: white;\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"    border: 1px solid #303030;\n"
"    border-radius: 0px;\n"
"    padding: 20px;\n"
"    min-width: 30px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5A5A5A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6A6A6A;\n"
"}")
        self.pushButton_division.setObjectName("pushButton_division")
        self.gridLayout_2.addWidget(self.pushButton_division, 0, 3, 1, 1)
        self.pushButton_1 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_1.setStyleSheet("QPushButton {\n"
"    background-color: #666666;\n"
"    color: white;\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"    border: 1px solid #303030;\n"
"    border-radius: 0px;\n"
"    padding: 20px;\n"
"    min-width: 30px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5A5A5A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6A6A6A;\n"
"}")
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout_2.addWidget(self.pushButton_1, 5, 0, 1, 1)
        self.pushButton_dot = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_dot.setStyleSheet("QPushButton {\n"
"    background-color: #666666;\n"
"    color: white;\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"    border: 1px solid #303030;\n"
"    border-radius: 0px;\n"
"    padding: 20px;\n"
"    min-width: 30px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5A5A5A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6A6A6A;\n"
"}")
        self.pushButton_dot.setObjectName("pushButton_dot")
        self.gridLayout_2.addWidget(self.pushButton_dot, 6, 2, 1, 1)
        self.pushButton_pm = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_pm.setStyleSheet("QPushButton {\n"
"    background-color: #404040;\n"
"    color: white;\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"    border: 1px solid #303030;\n"
"    border-radius: 0px;\n"
"    padding: 20px;\n"
"    min-width: 30px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5A5A5A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6A6A6A;\n"
"}\n"
"\n"
"")
        self.pushButton_pm.setObjectName("pushButton_pm")
        self.gridLayout_2.addWidget(self.pushButton_pm, 0, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #666666;\n"
"    color: white;\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"    border: 1px solid #303030;\n"
"    border-radius: 0px;\n"
"    padding: 20px;\n"
"    min-width: 30px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5A5A5A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6A6A6A;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 5, 1, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    background-color: #666666;\n"
"    color: white;\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"    border: 1px solid #303030;\n"
"    border-radius: 0px;\n"
"    padding: 20px;\n"
"    min-width: 30px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5A5A5A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6A6A6A;\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_2.addWidget(self.pushButton_9, 3, 2, 1, 1)
        self.pushButton_0 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_0.setStyleSheet("QPushButton {\n"
"    background-color: #666666;\n"
"    color: white;\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"    border: 1px solid #303030;\n"
"    border-radius: 0px;\n"
"    padding: 20px;\n"
"    min-width: 30px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5A5A5A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6A6A6A;\n"
"}")
        self.pushButton_0.setObjectName("pushButton_0")
        self.gridLayout_2.addWidget(self.pushButton_0, 6, 0, 1, 2)
        self.pushButton_multiple = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_multiple.setStyleSheet("QPushButton {\n"
"    background-color: #ffb833;\n"
"    color: white;\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"    border: 1px solid #303030;\n"
"    border-radius: 0px;\n"
"    padding: 20px;\n"
"    min-width: 30px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5A5A5A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6A6A6A;\n"
"}")
        self.pushButton_multiple.setObjectName("pushButton_multiple")
        self.gridLayout_2.addWidget(self.pushButton_multiple, 3, 3, 1, 1)
        self.pushButton_equal = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_equal.setStyleSheet("QPushButton {\n"
"    background-color: #ffb833;\n"
"    color: white;\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"    border: 1px solid #303030;\n"
"    border-radius: 0px;\n"
"    padding: 20px;\n"
"    min-width: 30px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5A5A5A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6A6A6A;\n"
"}")
        self.pushButton_equal.setObjectName("pushButton_equal")
        self.gridLayout_2.addWidget(self.pushButton_equal, 6, 3, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    background-color: #666666;\n"
"    color: white;\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"    border: 1px solid #303030;\n"
"    border-radius: 0px;\n"
"    padding: 20px;\n"
"    min-width: 30px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5A5A5A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6A6A6A;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_2.addWidget(self.pushButton_7, 3, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    background-color: #666666;\n"
"    color: white;\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"    border: 1px solid #303030;\n"
"    border-radius: 0px;\n"
"    padding: 20px;\n"
"    min-width: 30px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5A5A5A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6A6A6A;\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_2.addWidget(self.pushButton_8, 3, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: #666666;\n"
"    color: white;\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"    border: 1px solid #303030;\n"
"    border-radius: 0px;\n"
"    padding: 20px;\n"
"    min-width: 30px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5A5A5A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6A6A6A;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 5, 2, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: #666666;\n"
"    color: white;\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"    border: 1px solid #303030;\n"
"    border-radius: 0px;\n"
"    padding: 20px;\n"
"    min-width: 30px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5A5A5A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6A6A6A;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_2.addWidget(self.pushButton_5, 4, 1, 1, 1)
        self.pushButton_minus = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_minus.setStyleSheet("QPushButton {\n"
"    background-color: #ffb833;\n"
"    color: white;\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"    border: 1px solid #303030;\n"
"    border-radius: 0px;\n"
"    padding: 20px;\n"
"    min-width: 30px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5A5A5A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6A6A6A;\n"
"}")
        self.pushButton_minus.setObjectName("pushButton_minus")
        self.gridLayout_2.addWidget(self.pushButton_minus, 4, 3, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: #666666;\n"
"    color: white;\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"    border: 1px solid #303030;\n"
"    border-radius: 0px;\n"
"    padding: 20px;\n"
"    min-width: 30px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5A5A5A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6A6A6A;\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_2.addWidget(self.pushButton_6, 4, 2, 1, 1)
        self.pushButton_ac = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_ac.setStyleSheet("QPushButton {\n"
"    background-color: #404040;\n"
"    color: white;\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"    border: 1px solid #303030;\n"
"    border-radius: 0px;\n"
"    padding: 20px;\n"
"    min-width: 30px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5A5A5A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6A6A6A;\n"
"}\n"
"\n"
"")
        self.pushButton_ac.setObjectName("pushButton_ac")
        self.gridLayout_2.addWidget(self.pushButton_ac, 0, 2, 1, 1)
        self.pushButton_percentage = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_percentage.setStyleSheet("QPushButton {\n"
"    background-color: #404040;\n"
"    color: white;\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"    border: 1px solid #303030;\n"
"    border-radius: 0px;\n"
"    padding: 20px;\n"
"    min-width: 30px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5A5A5A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6A6A6A;\n"
"}\n"
"\n"
"")
        self.pushButton_percentage.setObjectName("pushButton_percentage")
        self.gridLayout_2.addWidget(self.pushButton_percentage, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(0, 0, 381, 91))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    color: white;\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"    border: 1px solid #303030;\n"
"    border-radius: 0px;\n"
"    background: rgba(38, 38, 38, 0.9);\n"
"    border: 1px solid #888;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 383, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_4.setText(_translate("MainWindow", "4"))
        self.pushButton_plus.setText(_translate("MainWindow", "+"))
        self.pushButton_division.setText(_translate("MainWindow", "÷"))
        self.pushButton_1.setText(_translate("MainWindow", "1"))
        self.pushButton_dot.setText(_translate("MainWindow", "."))
        self.pushButton_pm.setText(_translate("MainWindow", "±"))
        self.pushButton_2.setText(_translate("MainWindow", "2"))
        self.pushButton_9.setText(_translate("MainWindow", "9"))
        self.pushButton_0.setText(_translate("MainWindow", "0"))
        self.pushButton_multiple.setText(_translate("MainWindow", "×"))
        self.pushButton_equal.setText(_translate("MainWindow", "="))
        self.pushButton_7.setText(_translate("MainWindow", "7"))
        self.pushButton_8.setText(_translate("MainWindow", "8"))
        self.pushButton_3.setText(_translate("MainWindow", "3"))
        self.pushButton_5.setText(_translate("MainWindow", "5"))
        self.pushButton_minus.setText(_translate("MainWindow", "-"))
        self.pushButton_6.setText(_translate("MainWindow", "6"))
        self.pushButton_ac.setText(_translate("MainWindow", "AC"))
        self.pushButton_percentage.setText(_translate("MainWindow", "⌫"))
